# spring.application.name
spring:
  application:
    name: dubbo-auto-configure-consumer-sample
  # redis配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        ## 连接池中的最大空闲连接
        max-idle: 3
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最小空闲连接
        min-idle: 0
        ## 连接超时时间（毫秒）
    timeout: 1000
server:
  port: 8001

dubbo:
  registry:
    # 连接zookeeper 注册中心
    address: zookeeper://192.168.3.102:2181
      # 连接zookeeper 注册中心的节点
    group: dlamgroup
  # 因为dubbo连接servlet的时间只有一秒,只要超过一秒没被连接就会直接报错,所以就要把它连接的时间设置的长一点

  provider:
    timeout: 120000
